# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 		AaEzha
tagline:	Tambah Pinter, Gak Ditanggung
email: 		aaezha@gmail.com
author:
name:		Reza Nurfachmi
gems: ['jekyll-paginate']

description: > # this means to ignore newlines until "baseurl:"
  Sebuah blog yang, insya Allah, akan diisi dengan hal-hal yang baik
  dan berguna untuk para pembaca seluruhnya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaezha.github.io" # the base hostname & protocol for your site
twitter_username: AaEzha
github_username:  AaEzha

# Build settings
markdown: kramdown
highlighter: rouge